"""Parse Graphviz DOT layout into structured geometry for CFG visualization.

This module wraps ``dot -Tjson0`` to compute node positions, dimensions, and
edge spline control points from a ``.dot`` file produced by LLVM's
``opt -passes=dot-cfg``.

The output is a pure-data :class:`DotLayout` structure that the presentation
layer can map to Manim world coordinates.
"""

from __future__ import annotations

import json
import re
import subprocess
from dataclasses import dataclass, field
from pathlib import Path

from llvmanim.util.tools import find_tool


@dataclass(slots=True)
class DotNodeLayout:
    """Computed layout for a single DOT graph node (basic block)."""

    name: str
    center_x: float
    center_y: float
    width: float
    height: float
    label: str = ""


@dataclass(slots=True)
class DotEdgeLayout:
    """Computed layout for a single DOT graph edge."""

    source: str
    target: str
    spline_points: list[tuple[float, float]] = field(default_factory=list)
    label: str = ""
    tailport: str = ""


@dataclass(slots=True)
class DotLayout:
    """Complete layout output from Graphviz for a CFG."""

    nodes: dict[str, DotNodeLayout] = field(default_factory=dict)
    edges: list[DotEdgeLayout] = field(default_factory=list)
    bounding_box: tuple[float, float, float, float] = (0.0, 0.0, 1.0, 1.0)


class DotLayoutError(Exception):
    """Raised when DOT layout computation fails."""


def compute_dot_layout(dot_path: str | Path) -> DotLayout:
    """Run ``dot -Tjson0`` on a DOT file and return structured layout data.

    Parameters
    ----------
    dot_path:
        Path to a ``.dot`` file (typically generated by ``opt -passes=dot-cfg``).

    Returns
    -------
    DotLayout
        Node positions, edge splines, and bounding box in Graphviz point
        coordinates (1 point = 1/72 inch, y=0 at bottom).

    Raises
    ------
    DotLayoutError
        If the ``dot`` binary is not found, the file does not exist, or
        Graphviz returns a non-zero exit code.
    """
    path = Path(dot_path)
    if not path.exists():
        raise DotLayoutError(f"DOT file not found: {path}")

    try:
        dot = find_tool("dot")
        if dot is None:
            raise FileNotFoundError("Could not find dot tool")

        result = subprocess.run(
            [str(dot), "-Tjson0", str(path)],
            capture_output=True,
            text=True,
            check=True,
            timeout=30,
        )
    except FileNotFoundError as err:
        raise DotLayoutError(
            "Graphviz 'dot' binary not found. Install Graphviz to enable CFG layout."
        ) from err
    except subprocess.CalledProcessError as exc:
        raise DotLayoutError(
            f"dot exited with code {exc.returncode}: {exc.stderr.strip()}"
        ) from exc
    except subprocess.TimeoutExpired as err:
        raise DotLayoutError("dot layout computation timed out (30s)") from err

    try:
        raw = json.loads(result.stdout)
    except json.JSONDecodeError as exc:
        raise DotLayoutError(f"Failed to parse dot JSON output: {exc}") from exc

    return _parse_json_layout(raw)


def _extract_block_name(label: str) -> str:
    """Extract the block name from a Graphviz record label.

    LLVM DOT labels look like ``{entry:\\l|  %retval = ...\\l}``.
    The block name is the first word before ``:\\l``.
    """
    m = re.match(r"\{?\s*(\w[\w.]*)\s*:", label)
    return m.group(1) if m else label.strip("{} ").split(":")[0].strip() or "unknown"


def _parse_spline_points(pos_str: str) -> list[tuple[float, float]]:
    """Parse Graphviz spline position string into (x, y) tuples.

    Format: ``e,ex,ey x0,y0 x1,y1 x2,y2 ...``

    - ``e,ex,ey`` prefix is the arrow endpoint.
    - ``s,sx,sy`` prefix is the start override (rarely used).
    - Remaining pairs are cubic bezier control points.
    """
    parts = pos_str.strip().split()
    points: list[tuple[float, float]] = []
    endpoint: tuple[float, float] | None = None

    for part in parts:
        if part.startswith("e,"):
            vals = part[2:].split(",")
            endpoint = (float(vals[0]), float(vals[1]))
        elif part.startswith("s,"):
            continue
        else:
            coords = part.split(",")
            if len(coords) == 2:
                points.append((float(coords[0]), float(coords[1])))

    if endpoint is not None:
        points.append(endpoint)

    return points


def _parse_json_layout(raw: dict) -> DotLayout:
    """Convert parsed ``dot -Tjson0`` output into a :class:`DotLayout`."""
    bb_str = raw.get("bb", "0,0,1,1")
    bb = tuple(float(v) for v in bb_str.split(","))

    gvid_to_name: dict[int, str] = {}
    nodes: dict[str, DotNodeLayout] = {}

    for obj in raw.get("objects", []):
        gvid = obj["_gvid"]
        label = obj.get("label", "")
        raw_name = obj.get("name", "")

        # LLVM DOT uses opaque names like Node0x...; extract from record label.
        # Simple DOT files have label="\N" (graphviz default = use node name).
        if label and label != "\\N" and not label.startswith("\\N"):
            node_name = _extract_block_name(label)
        elif raw_name and raw_name != "\\N":
            node_name = raw_name
        else:
            node_name = f"node_{gvid}"

        gvid_to_name[gvid] = node_name

        cx, cy = (float(v) for v in obj["pos"].split(","))
        w = float(obj.get("width", "1")) * 72  # inches → points
        h = float(obj.get("height", "1")) * 72

        nodes[node_name] = DotNodeLayout(
            name=node_name,
            center_x=cx,
            center_y=cy,
            width=w,
            height=h,
            label=label,
        )

    edges: list[DotEdgeLayout] = []
    for edge_obj in raw.get("edges", []):
        src = gvid_to_name.get(edge_obj["tail"], "unknown")
        dst = gvid_to_name.get(edge_obj["head"], "unknown")
        pos_str = edge_obj.get("pos", "")
        spline = _parse_spline_points(pos_str) if pos_str else []

        tailport = edge_obj.get("tailport", "")
        label = ""
        if tailport == "s0":
            label = "T"
        elif tailport == "s1":
            label = "F"

        edges.append(
            DotEdgeLayout(
                source=src,
                target=dst,
                spline_points=spline,
                label=label,
                tailport=tailport,
            )
        )

    return DotLayout(
        nodes=nodes,
        edges=edges,
        bounding_box=bb,  # type: ignore[arg-type]
    )
