"""
CFG traversal animation sandbox — Manim Community Edition.

Uses LLVM's ``opt -passes=dot-cfg`` output + Graphviz layout engine to position
nodes and route edges accurately, then animates the runtime execution path
stepping through blocks one at a time using the trace entry_order.

Layout pipeline:
  1. Read a .dot file produced by ``opt -passes=dot-cfg``
  2. Run ``dot -Tjson0`` to compute layout (positions, splines, sizes)
  3. Map Graphviz point coordinates → Manim world coordinates
  4. Build block rectangles and edge bezier curves from layout data
  5. Animate traversal using the runtime trace

Visual design:
  - Unvisited blocks: dark gray fill, muted text
  - Active block: bright green fill, white text
  - Previously visited: light green fill, dark text
  - Unvisited edges: thin gray dashed
  - Traversed edges: solid bold blue
  - Active edge: yellow flash during traversal

Run (fast preview):
    uv run manim -ql sandbox/manim_CE/cfg_traversal.py CFGTraversal

Run (high quality):
    uv run manim -qh sandbox/manim_CE/cfg_traversal.py CFGTraversal

TODO: Add a --verbose / --show-ir flag that renders full IR instructions inside
each block instead of the summary.  For large functions, text fitting will need
auto-sizing or scrollable viewports — defer until layout engine is more mature.

TODO: Improvements to revisit:
  - Edge label placement: "true"/"false" labels occasionally overlap the edge
    curve or nearby blocks — investigate Graphviz xlabel or a label-collision
    avoidance pass.
  - Block text sizing: summary text can overflow narrow blocks on complex
    functions — add an auto-scale pass that measures text width vs block rect.
  - Arrowhead sizing: fixed 0.08 scale may be too large/small at different
    zoom levels — tie arrowhead scale to the coordinate mapper scale factor.
  - Color scheme: current green/blue palette is functional but not polished;
    consider a design-token system once the main tool implementation is stable.
  - Multi-function support: extend layout to handle inter-procedural CFGs
    (call edges, separate subgraphs per function).
  - Back-edge highlighting: distinguish back edges visually (e.g. red or
    dashed-dot) to make loops more obvious at a glance.
"""

from __future__ import annotations

import json
import re
import subprocess
from pathlib import Path

import numpy as np
from manim import (
    BOLD,
    DOWN,
    GREY_D,
    UP,
    WHITE,
    CubicBezier,
    DashedVMobject,
    FadeIn,
    FadeOut,
    RoundedRectangle,
    Scene,
    Text,
    Triangle,
    VGroup,
)

# ── Path to the .dot file (generated by opt -passes=dot-cfg) ──────────────────
_DOT_PATH = Path(__file__).resolve().parent.parent / "llvm_tools" / "graphviz" / ".main.dot"

# ── Runtime trace: ordered block visits ────────────────────────────────────────
# From double_trace.json, truncated to a few loop iterations for readability.
_ENTRY_ORDER = [
    "entry",
    "while.cond",
    "while.body",
    "while.cond",
    "while.body",
    "while.cond",
    "while.body",
    "while.cond",
    "while.end",
]

# ── Colours ────────────────────────────────────────────────────────────────────
_UNVISITED_FILL = "#555555"
_UNVISITED_TEXT = "#999999"
_ACTIVE_FILL = "#2ecc71"
_VISITED_FILL = "#d4edda"
_VISITED_TEXT = "#333333"
_EDGE_DORMANT = "#666666"
_EDGE_TRAVERSED = "#0056b3"
_EDGE_ACTIVE = "#f1c40f"


# ── DOT layout parser ─────────────────────────────────────────────────────────


def _run_dot_layout(dot_path: Path) -> dict:
    """Run ``dot -Tjson0`` on a .dot file and return parsed JSON layout."""
    result = subprocess.run(
        ["dot", "-Tjson0", str(dot_path)],
        capture_output=True,
        text=True,
        check=True,
        timeout=10,
    )
    return json.loads(result.stdout)


def _extract_block_name(label: str) -> str:
    """Extract the block name from a Graphviz record label.

    LLVM DOT labels look like: ``{entry:\\l|  %retval = ...\\l}``
    The block name is the first word before ``:\\l``.
    """
    m = re.match(r"\{?\s*(\w[\w.]*)\s*:", label)
    return m.group(1) if m else "unknown"


def _extract_block_summary(label: str) -> str:
    """Pull a short summary from the IR lines in a DOT label.

    Shows the terminator and any calls.
    """
    lines = label.replace("\\l", "\n").replace("{", "").replace("}", "").strip().split("\n")
    lines = [l.strip() for l in lines if l.strip() and not l.strip().startswith(("<", "T", "F"))]

    calls = []
    terminator = ""
    branch_cond = ""
    for line in lines:
        if "call " in line and "@llvm." not in line:
            m = re.search(r"@(\w+)", line)
            if m:
                calls.append(f"call @{m.group(1)}")
        if line.startswith("br "):
            terminator = line
            m = re.match(r"br i1 (%\w+),\s*label %(\w[\w.]*),\s*label %(\w[\w.]*)", line)
            if m:
                branch_cond = f"br i1 {m.group(1)}"
        elif line.startswith("ret "):
            terminator = line

    parts = []
    if calls:
        parts.extend(calls)
    if branch_cond:
        parts.append(branch_cond)
    elif terminator:
        parts.append(terminator)

    return "\n".join(parts) if parts else ""


def _parse_layout(
    layout: dict,
) -> tuple[
    dict[str, dict],
    list[dict],
    tuple[float, float, float, float],
]:
    """Parse Graphviz JSON0 layout into block and edge geometry."""
    bb = tuple(float(v) for v in layout["bb"].split(","))

    node_id_to_name: dict[int, str] = {}
    blocks: dict[str, dict] = {}

    for obj in layout["objects"]:
        gvid = obj["_gvid"]
        label = obj.get("label", "")
        block_name = _extract_block_name(label)
        node_id_to_name[gvid] = block_name

        px, py = (float(v) for v in obj["pos"].split(","))
        w = float(obj.get("width", "1")) * 72
        h = float(obj.get("height", "1")) * 72

        blocks[block_name] = {
            "pos": (px, py),
            "width": w,
            "height": h,
            "label": label,
            "summary": _extract_block_summary(label),
        }

    edges: list[dict] = []
    for edge in layout["edges"]:
        src = node_id_to_name[edge["tail"]]
        dst = node_id_to_name[edge["head"]]

        pos_str = edge["pos"]
        points = _parse_spline_points(pos_str)

        tailport = edge.get("tailport", "")
        label = ""
        if tailport == "s0":
            label = "T"
        elif tailport == "s1":
            label = "F"

        edges.append(
            {
                "src": src,
                "dst": dst,
                "points": points,
                "label": label,
            }
        )

    return blocks, edges, bb  # type: ignore[return-value]


def _parse_spline_points(pos_str: str) -> list[tuple[float, float]]:
    """Parse Graphviz spline position string into a list of (x, y) tuples.

    Format: ``e,ex,ey x0,y0 x1,y1 x2,y2 ...``
    The ``e,ex,ey`` prefix is the arrow endpoint; ``s,sx,sy`` is start point.
    """
    parts = pos_str.strip().split()
    points: list[tuple[float, float]] = []
    endpoint: tuple[float, float] | None = None

    for part in parts:
        if part.startswith("e,"):
            endpoint = tuple(float(v) for v in part[2:].split(","))  # type: ignore[assignment]
        elif part.startswith("s,"):
            pass  # start point — not used, first data point is the start
        else:
            coords = part.split(",")
            if len(coords) == 2:
                points.append((float(coords[0]), float(coords[1])))

    if endpoint:
        points.append(endpoint)

    return points


# ── Coordinate transform ──────────────────────────────────────────────────────


class _CoordMapper:
    """Map Graphviz point coordinates to Manim world coordinates.

    Graphviz: points (1/72 inch), y=0 at bottom.
    Manim: ~-7..+7 x, ~-4..+4 y, y=0 at center.
    """

    def __init__(self, bb: tuple[float, float, float, float]) -> None:
        x0, y0, x1, y1 = bb
        self._gv_w = x1 - x0 or 1.0
        self._gv_h = y1 - y0 or 1.0
        self._gv_cx = (x0 + x1) / 2
        self._gv_cy = (y0 + y1) / 2

        self._mn_w = 12.0
        self._mn_h = 6.5
        self._mn_cy = -0.3

        self._scale = min(self._mn_w / self._gv_w, self._mn_h / self._gv_h)

    def point(self, gv_x: float, gv_y: float) -> np.ndarray:
        """Convert a Graphviz (x, y) to Manim [x, y, 0]."""
        mx = (gv_x - self._gv_cx) * self._scale
        my = (gv_y - self._gv_cy) * self._scale + self._mn_cy
        return np.array([mx, my, 0.0])

    def size(self, gv_w: float, gv_h: float) -> tuple[float, float]:
        """Convert Graphviz width/height to Manim dimensions."""
        return gv_w * self._scale, gv_h * self._scale


# ── Mobject builders ───────────────────────────────────────────────────────────


def _build_block_mob(
    name: str,
    info: dict,
    mapper: _CoordMapper,
) -> VGroup:
    """Create a labeled rounded rectangle positioned by the Graphviz layout."""
    gv_x, gv_y = info["pos"]
    mn_w, mn_h = mapper.size(info["width"], info["height"])

    mn_w = max(mn_w, 1.5)
    mn_h = max(mn_h, 0.8)

    rect = RoundedRectangle(
        width=mn_w,
        height=mn_h,
        corner_radius=0.12,
        fill_color=_UNVISITED_FILL,
        fill_opacity=0.9,
        stroke_color=GREY_D,
        stroke_width=2,
    )

    title = Text(
        name,
        font="Monospace",
        font_size=20,
        weight=BOLD,
        color=_UNVISITED_TEXT,
    )

    summary = info["summary"]
    if summary:
        detail = Text(
            summary,
            font="Monospace",
            font_size=12,
            color=_UNVISITED_TEXT,
        )
        title.next_to(rect.get_top(), DOWN, buff=0.12)
        detail.next_to(title, DOWN, buff=0.08)
        if detail.width > mn_w - 0.3:
            detail.scale((mn_w - 0.3) / detail.width)
        group = VGroup(rect, title, detail)
    else:
        title.move_to(rect)
        group = VGroup(rect, title)

    center = mapper.point(gv_x, gv_y)
    group.move_to(center)
    return group


def _build_edge_mob(
    edge_info: dict,
    mapper: _CoordMapper,
) -> VGroup:
    """Create a bezier curve edge with arrowhead and optional label.

    Uses the Graphviz spline control points for accurate edge routing.
    Starts as dashed (dormant style).
    """
    points = edge_info["points"]
    if len(points) < 2:
        return VGroup()

    mn_points = [mapper.point(x, y) for x, y in points]

    # Build cubic bezier curve(s) from the control points
    if len(mn_points) >= 4:
        bezier = CubicBezier(
            mn_points[0],
            mn_points[1],
            mn_points[2],
            mn_points[3],
        )
        for i in range(4, len(mn_points) - 2, 3):
            if i + 2 < len(mn_points):
                end_idx = min(i + 3, len(mn_points) - 1)
                seg = CubicBezier(
                    mn_points[i],
                    mn_points[i + 1],
                    mn_points[i + 2],
                    mn_points[end_idx],
                )
                bezier.append_points(seg.points)
    else:
        bezier = CubicBezier(
            mn_points[0],
            mn_points[0] * 0.67 + mn_points[-1] * 0.33,
            mn_points[0] * 0.33 + mn_points[-1] * 0.67,
            mn_points[-1],
        )

    bezier.set_color(_EDGE_DORMANT)
    bezier.set_stroke(width=2)

    # Arrowhead at the end
    arrow_tip = Triangle(fill_opacity=1, fill_color=_EDGE_DORMANT, stroke_width=0)
    arrow_tip.scale(0.08)
    end_pt = bezier.point_from_proportion(1.0)
    near_end = bezier.point_from_proportion(0.92)
    direction = end_pt - near_end
    angle = np.arctan2(direction[1], direction[0])
    arrow_tip.rotate(angle - np.pi / 2)
    arrow_tip.move_to(end_pt)

    # Make path dashed for dormant state
    dashed_path = DashedVMobject(bezier, num_dashes=20)

    group = VGroup(dashed_path, arrow_tip)
    group.solid_curve = bezier  # type: ignore[attr-defined]
    group.arrow_tip = arrow_tip  # type: ignore[attr-defined]
    group.is_dashed = True  # type: ignore[attr-defined]

    if edge_info.get("label"):
        lbl = Text(
            edge_info["label"],
            font="Monospace",
            font_size=16,
            weight=BOLD,
            color=_EDGE_DORMANT,
        )
        label_pt = bezier.point_from_proportion(0.25)
        lbl.move_to(label_pt)
        tangent = bezier.point_from_proportion(0.3) - bezier.point_from_proportion(0.2)
        perp = np.array([-tangent[1], tangent[0], 0])
        norm = np.linalg.norm(perp)
        if norm > 0:
            lbl.shift(perp / norm * 0.22)
        group.add(lbl)
        group.edge_label = lbl  # type: ignore[attr-defined]

    return group


# ── Scene ──────────────────────────────────────────────────────────────────────


class CFGTraversal(Scene):
    """Animate a step-by-step CFG traversal for @main in double.ll.

    Layout is derived from LLVM's ``opt -passes=dot-cfg`` output processed
    through the Graphviz layout engine, ensuring accurate node positioning
    and edge routing.
    """

    def construct(self) -> None:
        self._block_mobs: dict[str, VGroup] = {}
        self._edge_groups: dict[tuple[str, str], VGroup] = {}
        self._visited: set[str] = set()
        self._traversed: set[tuple[str, str]] = set()

        layout = _run_dot_layout(_DOT_PATH)
        self._blocks, self._edges, bb = _parse_layout(layout)
        self._mapper = _CoordMapper(bb)

        self._draw_title()
        self._draw_graph()
        self.wait(0.5)
        self._animate_traversal()
        self.wait(2.0)

    def _draw_title(self) -> None:
        title = Text(
            "CFG Traversal  ·  @main  ·  double.ll",
            font_size=28,
            weight=BOLD,
        )
        title.to_edge(UP, buff=0.3)
        self.play(FadeIn(title, shift=DOWN * 0.2), run_time=0.5)

    def _draw_graph(self) -> None:
        """Create and fade in all block nodes and edge arrows."""
        for name, info in self._blocks.items():
            mob = _build_block_mob(name, info, self._mapper)
            self._block_mobs[name] = mob

        for edge_info in self._edges:
            group = _build_edge_mob(edge_info, self._mapper)
            self._edge_groups[(edge_info["src"], edge_info["dst"])] = group

        self.play(
            *[FadeIn(mob, scale=0.9) for mob in self._block_mobs.values()],
            run_time=0.8,
        )
        self.play(
            *[FadeIn(g) for g in self._edge_groups.values()],
            run_time=0.6,
        )

    def _activate_block(self, block_id: str) -> None:
        """Highlight a block as the currently executing block."""
        mob = self._block_mobs[block_id]
        rect = mob[0]
        text_mobs = list(mob[1:])

        anims = [
            rect.animate.set_fill(color=_ACTIVE_FILL, opacity=0.95).set_stroke(
                color=WHITE, width=3
            ),
        ]
        for t in text_mobs:
            anims.append(t.animate.set_color(WHITE))
        self.play(*anims, run_time=0.35)

    def _settle_block(self, block_id: str) -> None:
        """Transition from active to visited styling."""
        mob = self._block_mobs[block_id]
        rect = mob[0]
        text_mobs = list(mob[1:])

        anims = [
            rect.animate.set_fill(color=_VISITED_FILL, opacity=0.9).set_stroke(
                color=GREY_D, width=2
            ),
        ]
        for t in text_mobs:
            anims.append(t.animate.set_color(_VISITED_TEXT))
        self.play(*anims, run_time=0.25)

    def _traverse_edge(self, src: str, dst: str) -> None:
        """Flash an edge yellow then settle it to bold blue."""
        key = (src, dst)
        if key not in self._edge_groups:
            return
        group = self._edge_groups[key]

        if getattr(group, "is_dashed", False) and key not in self._traversed:
            dashed_mob = group[0]
            solid = group.solid_curve  # type: ignore[attr-defined]
            solid.set_color(_EDGE_ACTIVE).set_stroke(width=3.5)
            group.arrow_tip.set_fill(color=_EDGE_ACTIVE)  # type: ignore[attr-defined]

            self.remove(dashed_mob)
            group.submobjects[0] = solid
            self.add(solid)
            group.is_dashed = False  # type: ignore[attr-defined]

            self.play(
                solid.animate.set_color(_EDGE_ACTIVE).set_stroke(width=3.5),
                run_time=0.2,
            )
        else:
            curve = group[0]
            self.play(
                curve.animate.set_color(_EDGE_ACTIVE).set_stroke(width=3.5),
                group.arrow_tip.animate.set_fill(color=_EDGE_ACTIVE),  # type: ignore[attr-defined]
                run_time=0.2,
            )

        curve = group[0]
        self.play(
            curve.animate.set_color(_EDGE_TRAVERSED).set_stroke(width=3),
            group.arrow_tip.animate.set_fill(color=_EDGE_TRAVERSED),  # type: ignore[attr-defined]
            run_time=0.15,
        )

        if hasattr(group, "edge_label"):
            group.edge_label.set_color(_EDGE_TRAVERSED)  # type: ignore[attr-defined]
        self._traversed.add(key)

    def _animate_traversal(self) -> None:
        """Step through the entry_order, highlighting blocks and edges."""
        prev_block: str | None = None

        for i, block_id in enumerate(_ENTRY_ORDER):
            if prev_block is not None:
                self._traverse_edge(prev_block, block_id)

            if prev_block is not None and prev_block != block_id:
                self._settle_block(prev_block)

            self._activate_block(block_id)
            self._visited.add(block_id)

            if i == 0:
                self.wait(0.6)
            elif block_id == "while.end":
                self.wait(0.8)
            else:
                self.wait(0.3)

            prev_block = block_id

        if prev_block:
            self._settle_block(prev_block)
